USE app_gh;

INSERT INTO permiso (nombre) VALUES
('VER_EMPLEADOS'),
('CREAR_EMPLEADOS'),
('EDITAR_EMPLEADOS'),
('ELIMINAR_EMPLEADOS'),

('VER_USUARIOS'),
('CREAR_USUARIOS'),
('EDITAR_USUARIOS'),
('ELIMINAR_USUARIOS');
